### ISSUE TITLE
not working as expected if WAN proto is PPPoE

### ISSUE THREAD

**Issue by arc1986** [br101/pingcheck#11]
if we have the PPPoE uplink, openwrt will create a seperate "pppoe-wan" interface. So,

network config:
---------
config interface 'wan'
        option ifname 'eth0.2'
        option ports '1 6t'
        option proto 'pppoe'
        option username 'xxxxx'
        option password 'yyyyy'

ifconfig:
-----------
ifconfig pppoe-wan
pppoe-wan Link encap:Point-to-Point Protocol  
          inet addr:10.195.37.xx  P-t-P:10.195.0.1  Mask:255.255.255.255
          UP POINTOPOINT RUNNING NOARP MULTICAST  MTU:1492  Metric:1
          RX packets:694980 errors:0 dropped:3259 overruns:0 frame:0
          TX packets:732882 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:3 
          RX bytes:675992023 (644.6 MiB)  TX bytes:564937907 (538.7 MiB)
ifconfig eth0.2
eth0.2    Link encap:Ethernet  HWaddr 50:64:2B:57:xx:xx 
          inet6 addr: fe80::5264:2bff:fe57:15xx/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:715426 errors:0 dropped:2907 overruns:0 frame:0
          TX packets:759389 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:682560459 (650.9 MiB)  TX bytes:582011426 (555.0 MiB)

log:
-----
pingcheck 
Configured interface 'wan' interval 10 timeout 30 host google.com TCP (80)
Failed to add server object: Invalid argument

Init TCP ping on 'wan'
Interface 'wan' changed to OFFLINE
Scheduling 'offline' scripts for 'wan'
Running 'offline' scripts for 'wan'

tried changing the iface, but
-------
pingcheck 
Configured interface 'pppoe-wan' interval 10 timeout 30 host google.com TCP (80)
Failed to add server object: Invalid argument

Interface 'pppoe-wan' not found or error

So, how to use it for pppoe?

**Comment by br101** [comment]
Hi! Not sure exactly what's happening as I can't test with pppoe... But maybe the interface is supposed to be named 'wan' as in the network config...

**Comment by br101** [comment]
Oh sorry just realized you tried that... can you send me the output of  ubus call network.interface.wan status

**Comment by arc1986** [comment]
Thanks for your support @br101.

ubus call network.interface.wan status
{
        "up": true,
        "pending": false,
        "available": true,
        "autostart": true,
        "dynamic": false,
        "uptime": 2692,
        "l3_device": "pppoe-wan",
        "proto": "pppoe",
        "device": "eth0.2",
        "updated": [
                "addresses",
                "routes"
        ],
        "metric": 0,
        "dns_metric": 0,
        "delegation": true,
        "ipv4-address": [
                {
                        "address": "10.195.226.108",
                        "mask": 32,
                        "ptpaddress": "10.195.0.1"
                }
        ],
        "ipv6-address": [

        ],
        "ipv6-prefix": [

        ],
        "ipv6-prefix-assignment": [

        ],
        "route": [
                {
                        "target": "0.0.0.0",
                        "mask": 0,
                        "nexthop": "10.195.0.1",
                        "source": "0.0.0.0\/0"
                }
        ],
        "dns-server": [
                "103.219.204.27",
                "8.8.8.8"
        ],
        "dns-search": [

        ],
        "inactive": {
                "ipv4-address": [

                ],
                "ipv6-address": [

                ],
                "route": [

                ],
                "dns-server": [

                ],
                "dns-search": [

                ]
        },
        "data": {

        }
}

**Comment by br101** [comment]
And ifconfig, please...

**Comment by br101** [comment]
Does `ping -I pppoe-wan 8.8.8.8` work?

**Comment by br101** [comment]
`Failed to add server object: Invalid argument` ... could it be that another instance of pingcheck is already running?

**Comment by arc1986** [comment]
ping -I pppoe-wan 8.8.8.8
PING 8.8.8.8 (8.8.8.8): 56 data bytes
64 bytes from 8.8.8.8: seq=0 ttl=59 time=2.960 ms
64 bytes from 8.8.8.8: seq=1 ttl=59 time=2.595 ms
64 bytes from 8.8.8.8: seq=2 ttl=59 time=3.021 ms
64 bytes from 8.8.8.8: seq=3 ttl=59 time=2.862 ms
64 bytes from 8.8.8.8: seq=4 ttl=59 time=2.848 ms
64 bytes from 8.8.8.8: seq=5 ttl=59 time=2.859 ms
^C
--- 8.8.8.8 ping statistics ---
6 packets transmitted, 6 packets received, 0% packet loss

**Comment by arc1986** [comment]
> `Failed to add server object: Invalid argument` ... could it be that another instance of pingcheck is already running?

killed the existing process and start the new one, but,

Configured interface 'pppoe-wan' interval 10 timeout 30 host google.com TCP (80)
Interface 'pppoe-wan' not found or error
^C
pppoe-wan:	UNKNOWN  nan% (0/0 on )

with WAN:
Configured interface 'wan' interval 10 timeout 30 host google.com TCP (80)
Init TCP ping on 'wan'
Interface 'wan' changed to OFFLINE
Scheduling 'offline' scripts for 'wan'
Running 'offline' scripts for 'wan'

**Comment by arc1986** [comment]
as we have different WAN proto, can we use pingcheck on 'lan' interface?

config interface 'lan'
        option type 'bridge'
        option proto 'static'
        option netmask '255.255.255.0'
        option ip6assign '60'
        option ports '2 3 6t'
        option ipaddr '192.168.1.1'
        option ifname 'eth0.1'

Configured interface 'lan' interval 10 timeout 30 host google.com TCP (80)
Interface 'lan' has no default route but local one
Init TCP ping on 'lan'
^C
lan:	UP_WITHOUT_DEFAULT_ROUTE   0% (0/2 on br-lan)

**Comment by br101** [comment]
Okay, one by one
1) Failed to add server object: Invalid argument is solved by not running multiple instances of pingcheck
2) the 'wan' interface should be specified, as in your original test, pingcheck should get the right network interface (pppoe-wan) automatically - the problem seems to be there...
3) Yes, you should be able to use pingcheck on the 'lan' interface as well

I can not reproduce your setup, as I don't have pppoe... how could we debug this together? Can you contact me by email?

**Comment by br101** [comment]
4) Could you try ordinary ping (option protocol icmp) at first?

**Comment by br101** [comment]
I have pushed some changes to git - can you try them?

**Comment by arc1986** [comment]
used the latest version and its worked for pppoe :+1: ,

pingcheck 
Configured interface 'wan' interval 10 timeout 30 host google.com TCP (80)
Interface 'wan' changed to ONLINE
Scheduling 'online' scripts for 'wan'
Running 'online' scripts for 'wan'
wan pppoe-wan ONLINE master

**Comment by arc1986** [comment]
thanks for your support @br101 :-)

**Comment by br101** [comment]
Welcome

**Comment by rdslw** [comment]
@br101 just to let you know, current releases of openwrt still use pingcheck from 2017, and in result have this bug, rendering pingcheck not working for any openwrt user on pppoe-wan for example.

**Comment by br101** [comment]
Thanks, created https://github.com/openwrt/packages/pull/11976 for openwrt-19.07
