### ISSUE TITLE
opkg version outdated

### ISSUE THREAD

**Issue by strassea** [br101/pingcheck#12]
Hey I wanted to install you package via opkg and noticed it's outdated. Is it possible to push the up-to-date version to their repos?
Cheers

**Comment by br101** [comment]
OK, made a pull request for openwrt packages... it will first have to go thru master before appearing in 18.06 or 19.07...

https://github.com/openwrt/packages/pull/10804

**Comment by br101** [comment]
The update just got pulled into OpenWRT master

**Comment by strassea** [comment]
Thanks!
