### ISSUE TITLE
MAX_IFNAME_LEN not long enough

### ISSUE THREAD

**Issue by jonesmz** [br101/pingcheck#14]
lime-sdk configures some interfaces with quite long names.

E.g. lm_net_br_lan_anygw_if

16 characters seems arbitrary.

Can this be increased?

**Comment by br101** [comment]
Of course... would 64 chars do?

**Comment by jonesmz** [comment]
Yes, probably.

You might consider increasing it to 256, just so no one could ever realistically complain about it being too small again.

**Comment by jonesmz** [comment]
Wrong button, sorry.
