### ISSUE TITLE
ability to check multiple hosts instead of one per interface

### ISSUE THREAD

**Issue by rdslw** [br101/pingcheck#15]
Allow to monitor multiple hosts.

Proposal:
1. do not use interfaces
2. use 'name' as userdefined name (may be named whatever user wants, also 'wan' which wont break compability)
3. do not check if there is interface defined

**Comment by br101** [comment]
Sorry, this is not the use-case for pingcheck... i assume there are other tools to do this... pingcheck is made specifically to bind the ping to the interface, in order to know the interface status.
