### ISSUE TITLE
Online if hostname cannot be resolved

### ISSUE THREAD

**Issue by Xima** [br101/pingcheck#17]
When pingcheck fail to resolve hostname, it switch to online instead of offline.

I tried disconnecting the gsm antenna. when the host is set to an ip address it works fine. It goes to offline and run the scripts.
But if I put a hostname (example.com). It, of course, fails to resolve the host. but then switch to online... 

See the logs:

```
Configured interface 'wan_4' interval 120 timeout 240 host example.com ICMP (80)
Init ICMP ping on 'wan_4'
Failed to resolve
Interface 'wan_4' changed to ONLINE
Scheduling 'online' scripts for 'wan_4'
Running 'online' scripts for 'wan_4'
Failed to resolve
Failed to resolve
Failed to resolve
Failed to resolve
Failed to resolve
Failed to resolve
...
```

This means it only works correctly if it can resolve the hostname at initialization and lost he connection afterward. But doesn't works if it has no connection from the start. Which is an issue for our usage.

**Comment by br101** [comment]
Thank you for reporting, yes this was a bug and is fixed now.

**Comment by br101** [comment]
@Xima please confirm
