### ISSUE TITLE
How to setup so when ping to router (192.168.0.1) times out, will run offline script that runs wifi down and wifi up, and wait 10 seconds

### ISSUE THREAD

**Issue by kocoman1** [br101/pingcheck#19]
How to setup so when ping to router (192.168.0.1) times out, will run offline script that runs wifi down and wifi up, and wait 10 seconds

My wifi (repeater) is not working well. Not sure if its hw or sw problem. 

I would run...

opkg update
opkg install pingcheck
nano (edit) config file where? 

I am lost when i see the required section "interface" uci name of interface. What do i fill in there?

Also is ubus some kind of logger/history analyzer?

Thanks

**Comment by br101** [comment]
Its all documented in the README https://github.com/br101/pingcheck

**Comment by br101** [comment]
ubus is a inter process communication (IPC) like DBus
