### ISSUE TITLE
pingcheck fails on VPN without routes

### ISSUE THREAD

**Issue by gwax** [br101/pingcheck#3]
Certain OpenVPN connections do not register routes on the interface and use other mechanisms for managing traffic flow. These interfaces return an empty routes list.

when pingcheck initializes the interface, it registers the interface as NO_ROUTE: https://github.com/br101/pingcheck/blob/master/ping.c#L115

pingcheck assumes a ping will fail without actually checking.

However, a manual ping of the interface `ping -I ...` succeeds.

**Comment by br101** [comment]
should have been fixed with #8
