### ISSUE TITLE
Pingcheck crashes with standard config

### ISSUE THREAD

**Issue by riodda** [br101/pingcheck#4]
I've tryed to install pingcheck but i have recived and error message  

Sun Jul 23 11:59:18 2017 daemon.info procd: Instance pingcheck::instance1 s in a crash loop 6 crashes, 0 seconds since last crash

**Comment by br101** [comment]
Can you post the output when you run pingcheck manually? (/etc/init.d/pingcheck stop; pingcheck)

**Comment by riodda** [comment]
root@lede:~# pingcheck
Error relocating /usr/sbin/pingcheck: uloop_run_timeout: symbol not found
Error relocating /usr/sbin/pingcheck: ubus_invoke_fd: symbol not found

**Comment by PolynomialDivision** [comment]
what lede/openwrt release are you using?

**Comment by br101** [comment]
I just tested with LEDE master `reboot-5017-g2cb8f0a` and it worked. 
It looks like you are missing `libubus` and `libubox` packages or have different versions

**Comment by br101** [comment]
Works here
