### ISSUE TITLE
Pingcheck don't autostart

### ISSUE THREAD

**Issue by riodda** [br101/pingcheck#6]
Hi, i'm trying to play with pingcheck and i configured it and enable but it doesn't start
After reboot
`root@OpenWrt:/# ubus call pingcheck status`
`Command failed: Not found`

if i manullay issue pingcheck i have

`root@OpenWrt:/# pingcheck`
`Configured interface 'wan' interval 10 timeout 30 host 1daf825e`
`Configured interface 'wwan_4' interval 10 timeout 30 host 6389f3c2`
`Interface 'wan' not up`
`Init ping on 'wwan_4'`
`Interface 'wwan_4' changed to ONLINE`
`Scheduling 'online' scripts for 'wwan_4'`
`Running 'online' scripts for 'wwan_4'`
`^C`
`wan:    DOWN     -nan% (0/0 on )`
`wwan_4: ONLINE   100% (1/1 on usb0)`

If i log in the webui and i restart pingcheck 

root@OpenWrt:/# ubus call pingcheck status
{
        "status": "ONLINE",
        "online_interfaces": [
                "wwan_4"
        ],
        "known_interfaces": [
                "wan",
                "wwan_4"
        ]
}
root@OpenWrt:/#

If i reboot the box i'm back in the situation 
`root@OpenWrt:/# ubus call pingcheck status`
`Command failed: Not found`

**Comment by br101** [comment]
`/etc/init.d/pingcheck start`??? check your `/etc/rc.d`

**Comment by br101** [comment]
Works over here in default package
